run:
  go: "1.22"

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: (.+)_test\.go
      linters:
        - dupl
        - gomnd
        - lll
  exclude:
    - should have a package comment
    - should have comment
    - should be of the form
    - should not use dot imports
    - which can be annoying to use
    # Binds to all network interfaces
    - G102
    # Use of unsafe calls should be audited
    - G103
    # Errors unhandled
    - G104
    # file/folder Permission
    - G301
    - G302
    # Potential file inclusion via variable
    - G304
    # Deferring unsafe method like *os.File Close
    - G307
    # TLS MinVersion too low
    - G402
    # Use of weak random number generator math/rand
    - G404
    # Unused parameters
    - SA1019
    # defer return errors
    - SA5001

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
