run:
  go: "1.22"

linters:
  disable-all: true
  enable:
    - bodyclose
    # - depguard
    - dogsled
    - dupl
    - errcheck
    # - errorlint
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - godox
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    # - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: (.+)_test\.go
      linters:
        - dupl
        - gomnd
        - lll

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
