FROM golang:1.14-alpine
RUN apk add --no-cache ca-certificates git && \
  wget -qO/go/bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 && \
  chmod +x /go/bin/dep

WORKDIR /go/src/github.com/chanhteam/golang-service-example

COPY go.mod .
COPY go.sum .

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download

COPY . .

CMD CGO_ENABLED=0 go test -covermode=count ./... -v cover
