version: "2"

networks:
  default:
    external:
      name: docker

services:
  api:
    image: golang-service-sample:latest
    command: /api
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - default
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - GRPC_PORT=5000
      - HTTP_PORT=5001
      - LOG_LEVEL=-1
      - LOG_TIME_FORMAT=2006-01-02T15:04:05Z07:00

  worker:
    image: golang-service-sample:latest
    command: /worker
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - default

  migration:
    image: golang-service-sample:latest
    command: /migration
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - default

  mysql:
    image: mysql:5.7
    command: ["--max_connections=1000"]
    hostname: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=golang_sample
    ports:
      - "3306:3306"
    networks:
      - default
